# Configure job submission

output_path: output
template_file: julia_template.sh

models:
  - cnn
  # - resnet
  # - fno
  # - neuralPDE
  # - grind
  # - ptv1
  # - ptv3
  # - geo_fno
  # - pointgnn
  # - pointnet
  # - graphpde
  # - feast
  # - gcn
  # - gat

resolutions:
  - low
  # - medium
  # - high
  # - full

equations:
  - A
  # - B
  # - KS
  # - GD
  # - RD
  # - W

structure: grid
batches: 128
epochs: 10

wandblog: final
version: 0:1
submit_scripts: False


hydra:
  run:
    dir: ${output_path}/hydra/logs/${now:%Y-%m-%d}_${now:%H-%M-%S}