model:
  _target_: src.model._point._feast.FeaStNet
  input_size: ${InChannels}
  output_size: ${OutChannels}
  lookback: ${lookback}
  hidden_size: 190
  hidden_layers: 5
  input_layer_heads: 10
  hidden_layer_heads: 10
  output_layer_heads: 10
  spatial_dimensions: 2


structure: cloud
wrapper: ${graph_wrapper}
name: feast