model:
  _target_: src.model._grid._neural_operator.FourierNeuralOperator
  n_layers: 3
  n_modes: [8,8]
  width: 64
  in_channels: ${InChannels}
  out_channels: ${OutChannels}
  lookback: ${lookback}

structure: grid
wrapper: ${grid_wrapper}
name: fno