model:
  _target_: src.model._point._gat.GATNet
  input_size: ${InChannels}
  output_size: ${OutChannels}
  hidden_size: 512
  hidden_layers: 5
  spatial_dimensions: 2

structure: cloud
wrapper: ${graph_wrapper}
name: gat