model:
  _target_: src.model._point._gcn.GCN
  hidden_layers: 9
  input_size: ${InChannels}
  output_size: ${OutChannels}
  hidden_size: 512
  #dropout: 0.1
  #knn: 16

structure: cloud
wrapper: ${graph_wrapper}
name: gcn