model:
  _target_: src.model._grid._neuralpde.NeuralPDE
  input_dim: ${InChannels}
  output_dim: ${OutChannels}
  hidden_channels: 256
  hidden_layers: 3
  solver: {'method': euler, 'options': {'step_size': 0.1}}
  use_adjoint: False

structure: grid
type: grid
wrapper: ${grid_wrapper}
name: neuralPDE