model:
  _target_: src.model._baseline._baseline_persistance.BaselinePersistence_grid
  input_size: ${InChannels}
  output_size: ${OutChannels}
  lookback: ${lookback}
  spatial_dimensions: 2

structure: grid
type: grid
wrapper: ${grid_wrapper}
name: persistance_grid