model:
  _target_: src.model._point._point_net.PointNet
  input_size: ${InChannels}
  output_size: ${OutChannels}
  intermediate_hidden_size: 256
  hidden_size: 256
  local_nn_hidden_size: 256
  local_nn_hidden_layers: 3
  global_nn_hidden_size: 256
  global_nn_hidden_layers: 3
  hidden_layers: 3
  spatial_dimensions: 2

structure: cloud
wrapper: ${graph_wrapper}
name: pointnet