model:
  _target_: src.model._point.point_transformer._v1.PointTransformerV1
  input_dim: ${InChannels}
  output_dim: ${OutChannels}
  num_points: ${NPoints}
  num_blocks: 3
  num_neighbors: 16
  transformer_dim: 128

structure: cloud
type: point
wrapper: ${point_wrapper}
name: ptv1