model:  
  _target_: src.model._grid._resnet.ResNet
  input_size: ${InChannels}
  output_size: ${OutChannels}
  resblock_layers: 6
  resblock_channels: 128
  resblock_type: simple
  padding: 1
  padding_mode: circular
  kernel_size: 3
  activation: ReLU

structure: grid
type: grid
wrapper: ${grid_wrapper}
name: resnet