_target_: pytorch_lightning.Trainer

accelerator: ${device}
devices: 1
val_check_interval: ${ValCheckInterval}
limit_val_batches: ${val_batches}
limit_test_batches: ${test_batches}
limit_train_batches: ${train_batches}
log_every_n_steps: 10
max_epochs: ${Epochs}
default_root_dir: ${output_dir}

logger:
  - _target_: pytorch_lightning.loggers.TensorBoardLogger
    save_dir: ${output_dir}/tb_logs
    name: ${logdir}
    version: ${version_name}
  - _target_: pytorch_lightning.loggers.CSVLogger
    save_dir: ${output_dir}/csv_logs
    name: ${logdir}
  - _target_: pytorch_lightning.loggers.WandbLogger
    project: dynabench2-${wandblog}
    save_dir: ${output_dir}/wandb_logs
    name: ${logdir}
    settings:
      _target_: wandb.Settings
      init_timeout: 120
callbacks:
  - _target_: pytorch_lightning.callbacks.ModelCheckpoint
    filename: best_ckpt
    dirpath: ${output_dir}/checkpoints/${logdir}/best
    monitor: val_loss
    save_top_k: 1
    mode: min
  - _target_: pytorch_lightning.callbacks.ModelCheckpoint
    dirpath: ${output_dir}/checkpoints/${logdir}/last
    save_last: True
    monitor: step
    mode: max
    every_n_train_steps: 100
    save_top_k: 1