##################################################
# PARAMETERS that need to be changed
# - MODEL
# - EQUATION
# - RESOLUTION
##################################################
defaults:
  - trainer: trainer
  - dbiterator@dbiterator: dbiterator
  - dbiterator@transforms: transforms
  - resolution: low
  - equation: advection
  - model@grid_wrapper: grid_wrapper
  - model@point_wrapper: point_wrapper
  - model@graph_wrapper: graph_wrapper
  - model@no_wrapper: no_wrapper
  - model: zero_cloud
  - _self_

# Model
version: 0:0
wrapper: ${model.wrapper}
type: ${model.type}
version_name: ${model.name}:${equation.name}:${resolution.name}:${version}
Name: Dynabench_${version_name}
output_dir: output
logdir: ${Name}
wandblog: final #tests

# Data
Equation: ${equation.name}
InChannels: ${equation.channel}
OutChannels: ${equation.channel}
Structure: ${model.structure}
Resolution: ${resolution.name}
NPoints: ${resolution.nPoints}
NGrid: ${resolution.nGrid}
lookback: 4
Base_path_data: data
Batch_size: 2
TrainRollout: 1
TestRollout: 16
Workers: 16

# Training
device: cpu

Epochs: 10
LearningRate: 1e-3
WeightDecay: 1e-6

# Trainer
ValCheckInterval: 1.0
test_batches: 1.0
val_batches: 1.0
train_batches: 1.0


hydra:
  run:
    dir: ${output_dir}/hydra/${logdir}/${now:%Y-%m-%d}_${now:%H-%M-%S}
